### ISSUE TITLE
Occasional crash on song playback 

### ISSUE THREAD

**Issue by PKBeam** [PKBeam/Edda#4]
Stack trace:
```
Application: Edda.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.InvalidDataException: Ran out of packets?!
   at NVorbis.Ogg.PacketProvider.FindPacket(Int32 pageIndex, Int64& granulePos, GetPacketGranuleCount getPacketGranuleCount, Boolean isRecursed)
   at NVorbis.Ogg.PacketProvider.SeekTo(Int64 granulePos, Int32 preRoll, GetPacketGranuleCount getPacketGranuleCount)
   at NVorbis.StreamDecoder.SeekTo(Int64 samplePosition, SeekOrigin seekOrigin)
   at NAudio.Vorbis.VorbisSampleProvider.Seek(Int64 samplePosition)
   at NAudio.Vorbis.VorbisWaveReader.set_Position(Int64 value)
   at NAudio.Wave.WaveStream.set_CurrentTime(TimeSpan value)
   at Edda.MainWindow.PlaySong() in C:\Users\Vincent Liu\source\repos\RagnarockEditor\MainWindow.xaml.cs:line 1050
   at Edda.MainWindow.AppMainWindow_PreviewKeyDown(Object sender, KeyEventArgs e) in C:\Users\Vincent Liu\source\repos\RagnarockEditor\MainWindow.xaml.cs:line 349
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RagnarockEditor.App.Main()
   ```

**Comment by PKBeam** [comment]
Possibly caused by this:
https://github.com/NVorbis/NVorbis/issues/19

**Comment by PKBeam** [comment]
closed; the release of the new NAudio/Vorbis update fixes this bug
